apiVersion: v1
kind: Pod
metadata:
  name: jenkinspod
  labels:
    app: jenkins
spec:
  containers:
    - image: jenkins
      name: jenkins
      ports:
        - containerPort: 8080
          hostPort: 8080
      volumeMounts:
        - name: jenkinsvol
          mountPath: /var/lib/jenkins_home
  volumes:
    - name: jenkinsvol
      hostPath:
        path: jenkins-data
        type: DirectoryOrCreate